config/routes.rb
Rails.application.routes.draw do
  resources :raitings
  resources :ratings
  resources :ratings
  resources :assignments
  resources :courses
  resources :students
  resources :criteria
  resources :tools

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	has_and_belongs_to_many :courses, through: :assignment_course
	has_many :criteria
	accepts_nested_attributes_for :criteria
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show

  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
    @assignment.criteria.build
    @assignment.criteria[0].raitings.build
  end

  # GET /assignments/1/edit
  def edit
    @assignment.criteria.build
   # @assignment.criteria.raitings.build
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:title, :total_points, criteria_attributes:[:text, :weight, raitings_attributes:[:text, :grade_value, :position]])
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_criterium_fields.html.erb
<%= f.fields_for :criteria do |crit| %>
<div class="field">
  <%= crit.label 'Criteria Text' %>
  <%= crit.text_field :text %>
</div>
<div class="field">
  <%= crit.label 'Criteria Weight' %>
  <%= crit.text_field :weight %>%
</div>
<% end %>

app/views/assignments/_form.html.erb
<script type="text/javascript">
  function addCriteriaRow(assignment)
  {

  }

  function addRaitingColumn(criteria)
  {

  }

  $('document').ready(function(){
    $rubric = $('ruberic'); 
  }); 
</script>

<%= form_for(@assignment) do |f| %>
  
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="">
    <div class="eight">
      <%= f.label :title %>
      <%= f.text_field :title %>
    
      <%= f.label :total_points %>
      <%= f.text_field :total_points %>
    </div>
    <div class="four">
      <h3>Courses with this Assignment</h3>
      <% if @assignment.courses.empty? %>
        <p>No Courses use this Assignment</p>
      <% else %>
        <ul>
          <%= @assignment.courses.each do | course | %>
            <li><%= course.name %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </section>  
  <section class="rubric_container">
    <table class="rubric">
      <tbody>        
        <% @assignment.criteria.each do |crit| %>
          <tr>
            <td>
              <p><input type='text' placeholder='Criteria Text' data-criteria-id='<%= @assignment.id %>' class='criteria-text' value='<%= crit.text %>'></p>
              <p>Weight: <input type='text' placeholder='100.0' data-criteria-id='<%= crit.id %>' class='criteria-weight' value='<%= crit.weight %>'>%</p>
            </td>
            <%  
              crit.raitings.each do |r| %>
                <td>
                  <p><input type='text' placeholder='Raiting Text' data-criteria-id='<%= crit.id %>' data-raiting-id='<%= r.id %>' class='raiting-text' value='<%= r.text %>' /></p>
                  <p><input type='text' data-criteria-id='<%= crit.id %>' data-raiting-id='<%= r.id %>' class='raiting-grade_value' value='<%= r.grade_value %>' placeholder='0' />pts</p>
                </td>
            <% 
              end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <button class="ruberic-add-raiting"> &#9658; </button>
    <button class="ruberic-add-critera"> &#9660; </button>
  </section>
<% end %>

app/views/assignments/_raitings_fields.html.erb
<p><%= raiting.text_field :text, placeholder: 'raiting text' %></p>
<p><%= raiting.text_field :grade_value, placeholder: 'point value' %> pts</p>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Total points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.title %></td>
        <td><%= assignment.total_points %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @assignment.title %>
</p>

<p>
  <strong>Total points:</strong>
  <%= @assignment.total_points %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>