config/routes.rb
Rails.application.routes.draw do
  resources :raitings
  resources :ratings
  resources :ratings
  resources :assignments
  resources :courses
  resources :students
  resources :criteria
  resources :tools

end

app/models/raiting.rb
class Raiting < ActiveRecord::Base
  belongs_to :criterium
end

app/controllers/raitings_controller.rb
class RaitingsController < ApplicationController
  before_action :set_raiting, only: [:show, :edit, :update, :destroy]

  # GET /raitings
  # GET /raitings.json
  def index
    @raitings = Raiting.all
  end

  # GET /raitings/1
  # GET /raitings/1.json
  def show
  end

  # GET /raitings/new
  def new
    @raiting = Raiting.new
  end

  # GET /raitings/1/edit
  def edit
  end

  # POST /raitings
  # POST /raitings.json
  def create
    @raiting = Raiting.new(raiting_params)

    respond_to do |format|
      if @raiting.save
        format.html { redirect_to @raiting, notice: 'Raiting was successfully created.' }
        format.json { render :show, status: :created, location: @raiting }
      else
        format.html { render :new }
        format.json { render json: @raiting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raitings/1
  # PATCH/PUT /raitings/1.json
  def update
    respond_to do |format|
      if @raiting.update(raiting_params)
        format.html { redirect_to @raiting, notice: 'Raiting was successfully updated.' }
        format.json { render :show, status: :ok, location: @raiting }
      else
        format.html { render :edit }
        format.json { render json: @raiting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raitings/1
  # DELETE /raitings/1.json
  def destroy
    @raiting.destroy
    respond_to do |format|
      format.html { redirect_to raitings_url, notice: 'Raiting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raiting
      @raiting = Raiting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raiting_params
      params.require(:raiting).permit(:critera_id, :text, :grade_value, :position)
    end
end

app/helpers/raitings_helper.rb
module RaitingsHelper
end

app/views/raitings/_form.html.erb
<%= form_for(@raiting) do |f| %>
  <% if @raiting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raiting.errors.count, "error") %> prohibited this raiting from being saved:</h2>

      <ul>
      <% @raiting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :critera_id %><br>
    <%= f.text_field :critera_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/raitings/edit.html.erb
<h1>Editing Raiting</h1>

<%= render 'form' %>

<%= link_to 'Show', @raiting %> |
<%= link_to 'Back', raitings_path %>

app/views/raitings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Raitings</h1>

<table>
  <thead>
    <tr>
      <th>Critera</th>
      <th>Text</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @raitings.each do |raiting| %>
      <tr>
        <td><%= raiting.critera %></td>
        <td><%= raiting.text %></td>
        <td><%= raiting.position %></td>
        <td><%= link_to 'Show', raiting %></td>
        <td><%= link_to 'Edit', edit_raiting_path(raiting) %></td>
        <td><%= link_to 'Destroy', raiting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Raiting', new_raiting_path %>

app/views/raitings/new.html.erb
<h1>New Raiting</h1>

<%= render 'form' %>

<%= link_to 'Back', raitings_path %>

app/views/raitings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Critera:</strong>
  <%= @raiting.critera %>
</p>

<p>
  <strong>Text:</strong>
  <%= @raiting.text %>
</p>

<p>
  <strong>Position:</strong>
  <%= @raiting.position %>
</p>

<%= link_to 'Edit', edit_raiting_path(@raiting) %> |
<%= link_to 'Back', raitings_path %>